name: Node.js CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{secrets.DEPLOY_HOOK_URL}}
        webhook_secret: ${{secrets.DEPLOY_HOOK_KEY}}
  
    ci:
      runs-on: ubuntu-20.04
      container: lironavon/docker-puppeteer-container:14.16.0
      env:
        CI: true
      steps:
      # cache the dependencies from any node_modules directory
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/package-lock.json')}}
      # install the dependencies
      - name: install dependencies
        run: npm ci --ignore-scripts
      # run the tests
      - name: test
        run: npm test
    
