name: Node.js CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{secrets.DEPLOY_HOOK_URL}}
        webhook_secret: ${{secrets.DEPLOY_HOOK_KEY}}


  
    
