name: Automated Test CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  ci:
    runs-on: ubuntu-20.04
    container: lironavon/docker-puppeteer-container:14.16.0
    env:
      CI: true
    steps:
    # install the dependencies
    - name: install dependencies
      run: npm ci --ignore-scripts
    # run the tests
    - name: test
      run: npm test
    
